### PR TITLE
Publish to range-export-cli on npmjs

### PR DESCRIPTION
**Pull request by ghost**
#### Any background context you want to provide?

Changed the executable to `range-export-cli`, too. It cuts down on package/executable confusion and can always be changed back if we end up using `range-export` later.

The json file this produces is still called `range-export.json`.

#### Definition of Done:

- [ ] Code is easy to understand and conforms with Prettier & eslint configs
- [ ] Incomplete code is marked with TODOs
- [ ] Code is suitably instrumented with logging and metrics
- [ ] Documentation has been updated as appropriate
- [ ] Manifest has been updated and version incremented correctly
- [ ] [OWASP Top 10](https://www.owasp.org/index.php/Top_10-2017_Top_10) have been considered

### CODE REVIEW

**Comment by ghost** [comment]
https://www.npmjs.com/package/range-export-cli

**Comment by ghost** [comment]
Also I'll need help transferring the package to the Range npmjs org.

**Comment by dpup** [comment]
What do you need help with?

https://stackoverflow.com/questions/43007471/how-to-migrate-npm-package-to-an-organization-scope

**Comment by ghost** [comment]
@dpup Sorry, should have been more clear. Go to https://www.npmjs.com/settings/range-labs/teams and add the `range-export-cli` package to the team packages there.

I'm not an organization owner or team admin, so the "+ Add Existing Package" button doesn't appear for me. Even the cli command fails with a 403 when I try granting access.

https://docs.npmjs.com/managing-team-access-to-organization-packages#adding-package-access-to-a-team-using-the-cli

**Comment by dpup** [comment]
I don't have read/write permissions for `range-export-cli` so can't add it to the team. Can you do that through the npm CLI first.

**Comment by ghost** [comment]
Excellent. I was able to add the package with the admin permissions.

**Review by dpup — APPROVED** [review]

**Pull request merged**
