### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by ghost**
#### Any background context you want to provide?

This includes an upgrade to the range-sdk dependency.

I tested this locally by downloading my own check-ins.

#### Definition of Done:

- [ ] Code is easy to understand and conforms with Prettier & eslint configs
- [ ] Incomplete code is marked with TODOs
- [ ] Code is suitably instrumented with logging and metrics
- [ ] Documentation has been updated as appropriate
- [ ] Manifest has been updated and version incremented correctly
- [ ] [OWASP Top 10](https://www.owasp.org/index.php/Top_10-2017_Top_10) have been considered

### CODE REVIEW

**Comment by ghost** [comment]
Also it looks like the package is taken down from npmjs? https://www.npmjs.com/package/range-export

**Review by stephyeung — APPROVED** [review]
Changes look good.

I don't know what to do about the package being down… @dpup?

**Comment by dpup** [comment]
Oh, weird. I don't know either.

**Comment by dpup** [comment]
Maybe try re-pushing.

**Comment by ghost** [comment]
I've sent a message to npmjs.com's support team about it.

**Pull request merged**
